//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int IdCTHD { get; set; }
        public int SoLuong { get; set; }
        public int IdHD { get; set; }
        public string DVT { get; set; }
        public int DonGia { get; set; }
        public string TenVT { get; set; }
    
        public virtual HoaDonBanHang HoaDonBanHang { get; set; }
    }
}
