//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDDH_KH
    {
        public int IdCTDDH_KH { get; set; }
        public string TenVatTu { get; set; }
        public int SoLuong { get; set; }
        public int DonGia { get; set; }
        public Nullable<int> TongCong { get; set; }
        public int IdDDHKH { get; set; }
    
        public virtual DonDatHang_KH DonDatHang_KH { get; set; }
    }
}
