//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDDH_NCC
    {
        public int IdCTDDH_NCC { get; set; }
        public int IdDDHNCC { get; set; }
        public string TenVatTu { get; set; }
        public int SoLuong { get; set; }
        public string DVT { get; set; }
        public int DonGia { get; set; }
    
        public virtual DonDatHang_NCC DonDatHang_NCC { get; set; }
    }
}
