//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHang_KH
    {
        public DonDatHang_KH()
        {
            this.ChiTietDDH_KH = new HashSet<ChiTietDDH_KH>();
            this.PhieuXuatKhoes = new HashSet<PhieuXuatKho>();
        }
    
        public int IdDDHKH { get; set; }
        public int IdKH { get; set; }
        public int IdNV { get; set; }
        public string TenKH { get; set; }
        public Nullable<System.DateTime> ThoiGianGiaoHang { get; set; }
        public string DiaChi { get; set; }
        public string PTTT { get; set; }
        public int IdVT { get; set; }
    
        public virtual ICollection<ChiTietDDH_KH> ChiTietDDH_KH { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual ICollection<PhieuXuatKho> PhieuXuatKhoes { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
