//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHang_NCC
    {
        public DonDatHang_NCC()
        {
            this.ChiTietDDH_NCC = new HashSet<ChiTietDDH_NCC>();
            this.PhieuNhapKhoes = new HashSet<PhieuNhapKho>();
        }
    
        public int IdDDHNCC { get; set; }
        public int TongTien { get; set; }
        public string TenCongTy { get; set; }
        public System.DateTime ThoiGianGiaoHang { get; set; }
        public string DiaDiemGiaoHang { get; set; }
        public int IdNV { get; set; }
        public int IdNCC { get; set; }
    
        public virtual ICollection<ChiTietDDH_NCC> ChiTietDDH_NCC { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual ICollection<PhieuNhapKho> PhieuNhapKhoes { get; set; }
    }
}
