//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBanHang
    {
        public HoaDonBanHang()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }
    
        public int IdHD { get; set; }
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public Nullable<int> TienThueGTGT { get; set; }
        public string ThueSuatGTGT { get; set; }
        public System.DateTime NgayLapHoaDon { get; set; }
        public Nullable<int> TongCong { get; set; }
        public string HTTT { get; set; }
        public int IdPhieuXK { get; set; }
    
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual PhieuXuatKho PhieuXuatKho { get; set; }
    }
}
