//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CNPMDOANCUOIKIEntities : DbContext
    {
        public CNPMDOANCUOIKIEntities()
            : base("name=CNPMDOANCUOIKIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChiTietDDH_KH> ChiTietDDH_KH { get; set; }
        public DbSet<ChiTietDDH_NCC> ChiTietDDH_NCC { get; set; }
        public DbSet<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public DbSet<ChiTietPhieuNhapKho> ChiTietPhieuNhapKhoes { get; set; }
        public DbSet<ChiTietPhieuXuatKho> ChiTietPhieuXuatKhoes { get; set; }
        public DbSet<DonDatHang_KH> DonDatHang_KH { get; set; }
        public DbSet<DonDatHang_NCC> DonDatHang_NCC { get; set; }
        public DbSet<DonViTinh> DonViTinhs { get; set; }
        public DbSet<HoaDonBanHang> HoaDonBanHangs { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<PhieuXuatKho> PhieuXuatKhoes { get; set; }
        public DbSet<VatTu> VatTus { get; set; }
        public DbSet<PhieuNhapKho> PhieuNhapKhoes { get; set; }
    }
}
