//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapKho
    {
        public PhieuNhapKho()
        {
            this.ChiTietPhieuNhapKhoes = new HashSet<ChiTietPhieuNhapKho>();
        }
    
        public int IdPhieuNK { get; set; }
        public string TenNguoiNhap { get; set; }
        public Nullable<int> Tong { get; set; }
        public Nullable<System.DateTime> NgayNhapKho { get; set; }
        public int IdDDHNCC { get; set; }
    
        public virtual ICollection<ChiTietPhieuNhapKho> ChiTietPhieuNhapKhoes { get; set; }
        public virtual DonDatHang_NCC DonDatHang_NCC { get; set; }
    }
}
