//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VatTu
    {
        public int IdVT { get; set; }
        public int IdDVT { get; set; }
        public string TenVT { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public Nullable<int> GiaMua { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public int IdNCC { get; set; }
    
        public virtual DonViTinh DonViTinh { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
